version: '3.5'

name: dr-trottoir

services:
  postgres:
    container_name: dr-trottoir-postgres
    hostname: dr-trottoir-postgres
    image: postgres
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: admin
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: password
    volumes:
      - './volumes/postgres:/var/lib/postgresql/data'
    network_mode: "host"
    user: 1000:1000

  api:
    container_name: dr-trottoir-api
    hostname: dr-trottoir-api
    build:
      dockerfile: ./Dockerfile
      context: .
      target: "api_production"
    network_mode: "host"
    environment:
      DATABASE_URL: "postgresql://admin:password@localhost:5432/main?schema=public"
      FILE_STORAGE_DIRECTORY: "/files"
      CORS: "http://localhost:3000"
      DISABLE_AUTH: "false"
      ERROR_LOGGER: "true"
    restart: always
    volumes:
      - './volumes/files:/files'
    user: 1000:1000

  web:
    container_name: dr-trottoir-web
    hostname: dr-trottoir-web
    build:
      dockerfile: ./Dockerfile
      context: .
      target: "web_production"
      args:
        VUE_APP_API_SERVER_ADDRESS: "http://localhost:8080/"
        VUE_APP_IMGPROXY_PROTOCOL: http
        VUE_APP_IMGPROXY_LOCATION: localhost
        VUE_APP_IMGPROXY_PORT: 8081
        VUE_APP_IMGPROXY_ROOT: local
    network_mode: "host"
    user: 1000:1000

  imgproxy:
    container_name: dr-trottoir-imgproxy
    hostname: dr-trottoir-imgproxy
    image: darthsim/imgproxy
    environment:
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /images/.
      IMGPROXY_ALLOWED_SOURCES: local://
      IMGPROXY_DEVELOPMENT_ERRORS_MODE: 'true'
      IMGPROXY_MAX_SRC_RESOLUTION: 100
      IMGPROXY_JPEG_PROGRESSIVE: 'true'
      IMGPROXY_BIND: ":8081"
    volumes:
      - './volumes/files:/images:ro'
    network_mode: "host"
    user: 1000:1000
