name: API Linter

on:
    push:
        branches:
            - 'development'
            - 'main'
            - 'api/**'
    pull_request:
        branches:
            - 'development'
            - 'main'
            - 'api/**'

jobs:
    lint:
        runs-on: [self-hosted]
        defaults:
            run:
                working-directory: ./api
        steps:
            - uses: actions/checkout@v3
            - name: "Check for linting and errors"
              run: npm ci && npm run test
