name: API Test
on:
    workflow_dispatch:
    pull_request:
        branches:
            - 'develop'
            - 'main'
            - 'api/**'
jobs:
    api-test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./api
        env:
            DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/main"
            NODE_ENV: "test"

        services:
            postgres:
                image: postgres
                # Set health checks to wait until postgres has started
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432
                env:
                    POSTGRES_DB: main
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
        steps:
            -   name: "Checkout the repo code"
                uses: actions/checkout@v3
            -   uses: actions/setup-node@v3
            -   name: "Clean install"
                run: npm ci
            -   name: "Setup the database"
                working-directory: ./orm
                run: |
                    npm install
                    npx prisma db push
            -   name: "Execute tests"
                run: npm run test
            -   name: "Upload CodeCov"
                run: | 
                    curl -Os https://uploader.codecov.io/latest/linux/codecov
                    chmod +x codecov
                    ./codecov
