name: API Linter

on:
    workflow_dispatch:
    pull_request:
        branches:
            - 'develop'
            - 'main'
            - 'api/**'

jobs:
    lint:
        runs-on: [ self-hosted ]
        env:
            PRISMA_SKIP_POSTINSTALL_GENERATE: true
            OUTPUT_DIRECTORY: ./api/prisma
        defaults:
            run:
                working-directory: ./api
        steps:
            -   uses: actions/checkout@v3
            -   name: "Check for linting and errors"
                run: npm run lint
            -   name: "Generate prisma schema"
                run: npx prisma generate
            -   name: "Run API tests"
                run: npm run test
