name: API Linter

on:
    workflow_dispatch:
    pull_request:
        branches:
            - 'develop'
            - 'main'
            - 'api/**'

jobs:
    lint_test:
        runs-on: [ self-hosted ]
        defaults:
            run:
                working-directory: ./api
        steps:
            -   name: "Checkout"
                uses: actions/checkout@v3
            -   name: NPM Registry Login
                uses: healthplace/npmrc-registry-login-action@v1.0.9
                with:
                  scope: "@selab-2"
                  registry: "https://npm.pkg.github.com"
                  auth-token: ${{ secrets.GITHUB_TOKEN }}
            -   name: "Install dependencies"
                run: npm ci
            -   name: "Check for linting and errors"
                run: npm run lint
