name: API Linter

on:
    push:
        branches:
            - 'development'
            - 'main'
            - 'api/**'
    pull_request:
        branches:
            - 'development'
            - 'main'
            - 'api/**'

jobs:
    build:
        runs-on: self-hosted
        defaults:
            run:
                working-directory: ./api
        steps:
            - uses: actions/checkout@v3
            - run: npm ci
            - run: npm test
