name: API Linter

on:
    workflow_dispatch:
    pull_request:
        branches:
            - 'develop'
            - 'main'
            - 'api/**'

jobs:
    lint-build:
        runs-on: [ self-hosted ]
        defaults:
            run:
                working-directory: ./api
        steps:
            -   name: "Checkout"
                uses: actions/checkout@v3
            -   uses: actions/setup-node@v3
                with:
                    node-version: '16.x'
                    registry-url: 'https://npm.pkg.github.com'
                    scope: '@selab-2'
            -   name: "Install dependencies"
                run: npm ci
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            -   name: "Check for linting and errors"
                run: npm run lint
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            -   name: "Verify the code compiles"
                run: npm run build
            -   name: "Cleanup"
                if: always()
                run: |
                    chmod +x ../scripts/cleanup.sh
                    ../scripts/cleanup.sh -p
                shell: bash

