name: API Linter

on:
    workflow_dispatch:
    push:
        branches:
            - 'develop'
            - 'main'
    pull_request:
        branches:
            - 'develop'
            - 'main'
            - 'api/**'

jobs:
    lint-build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./api
        steps:
            -   name: "Checkout"
                uses: actions/checkout@v3
            -   uses: actions/setup-node@v3
            -   name: "Install dependencies"
                run: npm ci
            -   name: "Check for linting and errors"
                run: npm run lint
            -   name: "Verify the code compiles"
                run: npm run build
