name: Cleanup
on:
    workflow_call:

jobs:
    cleanup:
        name: Execute cleanup script
        runs-on: self-hosted
        steps:
            -   run: scripts/cleanup.sh
                shell: bash
