name: Docker Build

on:
    workflow_dispatch:
    push:
        branches:
            - 'develop'
            - 'main'
    pull_request:

jobs:
    docker-build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: .

        steps:
            -   name: "Checkout"
                uses: actions/checkout@v3
            -   name: "Build images"
                run: docker build . --rm=false
