name: API Linter

on:
    workflow_dispatch:
    push:
        branches:
            - 'development'
            - 'main'
            - 'web/**'
    pull_request:
        branches:
            - 'development'
            - 'main'
            - 'web/**'

jobs:
    lint:
        runs-on: [self-hosted]
        env:
          PRISMA_SKIP_POSTINSTALL_GENERATE: true
          OUTPUT_DIRECTORY: ./api/prisma
        defaults:
            run:
                working-directory: ./api
        steps:
            - uses: actions/checkout@v3
            - name: "Check for linting and errors"
              run: npm ci && npx prisma generate && npm run test
