name: Web Linter

on:
    workflow_dispatch:
    pull_request:
        branches:
            - 'develop'
            - 'main'
            - 'web/**'

jobs:
    web-lint:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./web
        steps:
            -   name: "Checkout"
                uses: actions/checkout@v3
            -   uses: actions/setup-node@v3
                with:
                    node-version: '16.x'
                    registry-url: 'https://npm.pkg.github.com'
                    scope: '@selab-2'
            -   name: "Install dependencies"
                run: npm ci
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            -   name: "Check for build errors"
                run: npm run build
                #            -   name: "Check for linting and errors"
                #                run: npm run test
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            -   name: "Cleanup"
                if: always()
                run: |
                    chmod +x ../server/cleanup.sh
                    ../server/cleanup.sh -p
                shell: bash
