name: Web Linter

on:
    workflow_dispatch:
    push:
        branches:
            - 'develop'
            - 'main'
            - 'web/**'
    pull_request:
        branches:
            - 'develop'
            - 'main'
            - 'web/**'

jobs:
    lint:
        runs-on: [self-hosted]
        defaults:
            run:
                working-directory: ./web
        steps:
            - uses: actions/checkout@v3
            - name: "Check for linting and errors"
              run: npm ci && npm run test
