name: Web Linter

on:
    workflow_dispatch:
    push:
        branches:
            - 'develop'
            - 'main'
    pull_request:
        branches:
            - 'develop'
            - 'main'
            - 'web/**'

jobs:
    web-lint:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./web
        steps:
            -   name: "Checkout"
                uses: actions/checkout@v3
            -   uses: actions/setup-node@v3
            -   name: "Generate Query Builder"
                run: cd ../api_query && npm ci && cd ../web
            -   name: "Install dependencies"
                run: npm ci
            -   name: "Check for build errors"
                run: npm run build
            -   name: "Check for linting and errors"
                run: npm run test
